---
title: iris
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---


# About the dataset {.unnumbered #about}

```{r echo = FALSE, message = FALSE, warning = FALSE}

library(fabR)
library(madshapR)
library(DT)
library(dplyr)
library(tidyr)
library(stringr)

load(file = paste0("/staff/gfabre/test-iris2/myrepo/temp_bookdown_report/bookdown_report.RData"))

```
--------------------------------------------------------------------------------


## Overview

```{r echo = FALSE, message = FALSE, warning = FALSE}

datatable(.summary_var$Overview, colnames = rep("",ncol(.summary_var$Overview)),
    options = list(pageLength = nrow(.summary_var$Overview),scrollX = TRUE),
    rownames = FALSE,escape = FALSE)

```

--------------------------------------------------------------------------------


## Variables summary


```{r echo = FALSE, message = FALSE, warning = FALSE}


# if(toc == "variables"){

  datatable(
    data_dict_flat %>%
      mutate(
        name = ifelse(name %in% col_id, name, paste0(
        "<a href=\"./var",`index in data dict.`,".html\" >",name,"</a>"))),
    options=list(scrollX = TRUE,pageLength=20),rownames = FALSE,escape = FALSE)

# }else{
# 
#   datatable(
#     data_dict_flat,
#     options = 
#       list(scrollX = TRUE, pageLength=20),rownames = FALSE,escape = FALSE)
# 
# }

```

--------------------------------------------------------------------------------



<!--chapter:end:index.Rmd-->

# Sepal.Length{.unnumbered #var1}


**VARIABLE CHARACTERISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}


  datatable(t(
     data_dict$Variables %>%
     filter(name == 'Sepal.Length')),
   options = list(dom = 't', scrollX = TRUE, ordering = FALSE,paging = FALSE),
   rownames = TRUE, colnames = rep('', 2),filter = 'none' ,  escape = FALSE)
```

</div>



----------------------------------------------------------------------

**SUMMARY STATISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
 plots <- variable_visualize(
  dataset,
  col = 'Sepal.Length',
  data_dict = data_dict, 
  group_by = '',
  .summary_var = .summary_var)       
        
  if(!is.null(plots$summary_table))      plots$summary_table                  
```

</div>


<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
  if(!is.null(plots$summary_categories)) plots$summary_categories             
```

</div>


---------------------------------------------------------------------

**VISUAL REPRESENTATION**

```{r, figures-plot12-1, fig.show='hold',fig.align = 'center',echo = FALSE,message = FALSE, warning = FALSE, results='hide'}

        
if(!is.null(plots$main_values_1))      plots$main_values_1
if(!is.null(plots$main_values_2))      plots$main_values_2
if(!is.null(plots$cat_values))         plots$cat_values
if(!is.null(plots$missing_values))     plots$missing_values
if(!is.null(plots$pie_values))         plots$pie_values                       
```


<!--chapter:end:01-Sepal.Length.Rmd-->

# Sepal.Width{.unnumbered #var2}


**VARIABLE CHARACTERISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}


  datatable(t(
     data_dict$Variables %>%
     filter(name == 'Sepal.Width')),
   options = list(dom = 't', scrollX = TRUE, ordering = FALSE,paging = FALSE),
   rownames = TRUE, colnames = rep('', 2),filter = 'none' ,  escape = FALSE)
```

</div>



----------------------------------------------------------------------

**SUMMARY STATISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
 plots <- variable_visualize(
  dataset,
  col = 'Sepal.Width',
  data_dict = data_dict, 
  group_by = '',
  .summary_var = .summary_var)       
        
  if(!is.null(plots$summary_table))      plots$summary_table                  
```

</div>


<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
  if(!is.null(plots$summary_categories)) plots$summary_categories             
```

</div>


---------------------------------------------------------------------

**VISUAL REPRESENTATION**

```{r, figures-plot12-2, fig.show='hold',fig.align = 'center',echo = FALSE,message = FALSE, warning = FALSE, results='hide'}

        
if(!is.null(plots$main_values_1))      plots$main_values_1
if(!is.null(plots$main_values_2))      plots$main_values_2
if(!is.null(plots$cat_values))         plots$cat_values
if(!is.null(plots$missing_values))     plots$missing_values
if(!is.null(plots$pie_values))         plots$pie_values                       
```


<!--chapter:end:02-Sepal.Width.Rmd-->

# Petal.Length{.unnumbered #var3}


**VARIABLE CHARACTERISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}


  datatable(t(
     data_dict$Variables %>%
     filter(name == 'Petal.Length')),
   options = list(dom = 't', scrollX = TRUE, ordering = FALSE,paging = FALSE),
   rownames = TRUE, colnames = rep('', 2),filter = 'none' ,  escape = FALSE)
```

</div>



----------------------------------------------------------------------

**SUMMARY STATISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
 plots <- variable_visualize(
  dataset,
  col = 'Petal.Length',
  data_dict = data_dict, 
  group_by = '',
  .summary_var = .summary_var)       
        
  if(!is.null(plots$summary_table))      plots$summary_table                  
```

</div>


<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
  if(!is.null(plots$summary_categories)) plots$summary_categories             
```

</div>


---------------------------------------------------------------------

**VISUAL REPRESENTATION**

```{r, figures-plot12-3, fig.show='hold',fig.align = 'center',echo = FALSE,message = FALSE, warning = FALSE, results='hide'}

        
if(!is.null(plots$main_values_1))      plots$main_values_1
if(!is.null(plots$main_values_2))      plots$main_values_2
if(!is.null(plots$cat_values))         plots$cat_values
if(!is.null(plots$missing_values))     plots$missing_values
if(!is.null(plots$pie_values))         plots$pie_values                       
```


<!--chapter:end:03-Petal.Length.Rmd-->

# Petal.Width{.unnumbered #var4}


**VARIABLE CHARACTERISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}


  datatable(t(
     data_dict$Variables %>%
     filter(name == 'Petal.Width')),
   options = list(dom = 't', scrollX = TRUE, ordering = FALSE,paging = FALSE),
   rownames = TRUE, colnames = rep('', 2),filter = 'none' ,  escape = FALSE)
```

</div>



----------------------------------------------------------------------

**SUMMARY STATISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
 plots <- variable_visualize(
  dataset,
  col = 'Petal.Width',
  data_dict = data_dict, 
  group_by = '',
  .summary_var = .summary_var)       
        
  if(!is.null(plots$summary_table))      plots$summary_table                  
```

</div>


<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
  if(!is.null(plots$summary_categories)) plots$summary_categories             
```

</div>


---------------------------------------------------------------------

**VISUAL REPRESENTATION**

```{r, figures-plot12-4, fig.show='hold',fig.align = 'center',echo = FALSE,message = FALSE, warning = FALSE, results='hide'}

        
if(!is.null(plots$main_values_1))      plots$main_values_1
if(!is.null(plots$main_values_2))      plots$main_values_2
if(!is.null(plots$cat_values))         plots$cat_values
if(!is.null(plots$missing_values))     plots$missing_values
if(!is.null(plots$pie_values))         plots$pie_values                       
```


<!--chapter:end:04-Petal.Width.Rmd-->

# Species{.unnumbered #var5}


**VARIABLE CHARACTERISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}


  datatable(t(
     data_dict$Variables %>%
     filter(name == 'Species')),
   options = list(dom = 't', scrollX = TRUE, ordering = FALSE,paging = FALSE),
   rownames = TRUE, colnames = rep('', 2),filter = 'none' ,  escape = FALSE)
```

</div>


* **Categories**: 


<div style= "display:flex; margin:auto" > 


```{r echo = FALSE, message = FALSE, warning = FALSE}

                   
  datatable(
    data_dict$Categories %>% 
      filter(variable == 'Species') %>%
    select(variable, name, 
    matches(c('^label$','^label:[[:alnum:]]'))[1], missing) %>%
    mutate(across(everything(), as.character)),
    options = list(scrollX = TRUE),rownames = FALSE)                          
```

</div>



----------------------------------------------------------------------

**SUMMARY STATISTICS**

<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
 plots <- variable_visualize(
  dataset,
  col = 'Species',
  data_dict = data_dict, 
  group_by = '',
  .summary_var = .summary_var)       
        
  if(!is.null(plots$summary_table))      plots$summary_table                  
```

</div>


<div style= "display:flex; margin:auto" > 


```{r echo = FALSE,message = FALSE,warning = FALSE,knitr.figure = TRUE}

        
  if(!is.null(plots$summary_categories)) plots$summary_categories             
```

</div>


---------------------------------------------------------------------

**VISUAL REPRESENTATION**

```{r, figures-plot12-5, fig.show='hold',fig.align = 'center',echo = FALSE,message = FALSE, warning = FALSE, results='hide'}

        
if(!is.null(plots$main_values_1))      plots$main_values_1
if(!is.null(plots$main_values_2))      plots$main_values_2
if(!is.null(plots$cat_values))         plots$cat_values
if(!is.null(plots$missing_values))     plots$missing_values
if(!is.null(plots$pie_values))         plots$pie_values                       
```


<!--chapter:end:05-Species.Rmd-->

